<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="2" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-16T15:48:12 IST" name="Suite" finished-at="2024-10-16T15:48:23 IST" duration-ms="11290">
    <groups>
      <group name="errorHandling">
        <method signature="ErrorValidations.submitOrder()[pri:0, instance:Dirash_Company.Ecommerce_Framework.ErrorValidations@351d00c0]" name="submitOrder" class="Dirash_Company.Ecommerce_Framework.ErrorValidations"/>
      </group> <!-- errorHandling -->
    </groups>
    <test started-at="2024-10-16T15:48:12 IST" name="Submit Order Test" finished-at="2024-10-16T15:48:12 IST" duration-ms="10">
    </test> <!-- Submit Order Test -->
    <test started-at="2024-10-16T15:48:12 IST" name="Error validation Test" finished-at="2024-10-16T15:48:23 IST" duration-ms="11290">
      <class name="Dirash_Company.Ecommerce_Framework.ErrorValidations">
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:Dirash_Company.Ecommerce_Framework.ErrorValidations@351d00c0]" started-at="2024-10-16T15:48:12 IST" name="LaunchApplication" finished-at="2024-10-16T15:48:17 IST" duration-ms="4644" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method retried="true" signature="submitOrder()[pri:0, instance:Dirash_Company.Ecommerce_Framework.ErrorValidations@351d00c0]" started-at="2024-10-16T15:48:17 IST" name="submitOrder" finished-at="2024-10-16T15:48:18 IST" duration-ms="788" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Dirash_Company.Ecommerce_Framework.ErrorValidations.submitOrder(ErrorValidations.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Dirash_Company.Ecommerce_Framework.ErrorValidations@351d00c0]" started-at="2024-10-16T15:48:18 IST" name="closeBrowser" finished-at="2024-10-16T15:48:18 IST" duration-ms="221" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:Dirash_Company.Ecommerce_Framework.ErrorValidations@351d00c0]" started-at="2024-10-16T15:48:18 IST" name="LaunchApplication" finished-at="2024-10-16T15:48:22 IST" duration-ms="4034" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="submitOrder()[pri:0, instance:Dirash_Company.Ecommerce_Framework.ErrorValidations@351d00c0]" started-at="2024-10-16T15:48:22 IST" name="submitOrder" finished-at="2024-10-16T15:48:23 IST" duration-ms="1374" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Dirash_Company.Ecommerce_Framework.ErrorValidations.submitOrder(ErrorValidations.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Dirash_Company.Ecommerce_Framework.ErrorValidations@351d00c0]" started-at="2024-10-16T15:48:23 IST" name="closeBrowser" finished-at="2024-10-16T15:48:23 IST" duration-ms="166" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Dirash_Company.Ecommerce_Framework.ErrorValidations -->
    </test> <!-- Error validation Test -->
  </suite> <!-- Suite -->
</testng-results>
